<a href="https://colab.research.google.com/github/LahiruTjay/neural-networks-and-deep-learning/blob/master/intro_to_tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to Tensorflow

In [0]:
import numpy as np
import tensorflow as tf

In [2]:
print("Tensorflow version: {}".format(tf.__version__))

Tensorflow version: 1.13.1


## TF Constant

In [3]:
first_str = tf.constant('Lahiru')
second_str = tf.constant('Liyanapathirana')
third_str = tf.constant('is awesome')

final_str = first_str +  " " + second_str + " " + third_str
type(final_str)

tensorflow.python.framework.ops.Tensor

In [4]:
with tf.Session() as sess:
  result = sess.run(final_str)
  print(result)

b'Lahiru Liyanapathirana is awesome'


In [0]:
matrix1 = tf.constant([[1,3], 
                       [2,6]])
matrix2 = tf.constant([[13,26], 
                       [23,52]])
mat_mul = tf.matmul(matrix1, matrix2)

In [6]:
with tf.Session() as sess:
  result = sess.run(mat_mul)
  print(result)

[[ 82 182]
 [164 364]]


## TF Placeholder

In [0]:
num1 = tf.placeholder(tf.int32)
num2 = tf.placeholder(tf.int32)
add = tf.add(num1, num2)

In [8]:
with tf.Session() as sess:
  result = sess.run(add, feed_dict={num1:2, num2:3})
  print(result)

5


In [0]:
n1 = tf.placeholder(tf.int32)
n2 = tf.placeholder(tf.int32)

In [0]:
n_add = tf.add(n1, n2)
n_sub = tf.subtract(n_add, tf.constant(5))
n_mul = tf.multiply(n_sub, n1)

In [11]:
with tf.Session() as sess:
  result = sess.run(n_mul, feed_dict={n1:10, n2:20})
  print(result)

250


## TF Variable

In [12]:
p = tf.placeholder(tf.float32, shape = [], name = "p")
v2 = tf.Variable(2. , name = "v2")
a = tf.add(p, v2)

Instructions for updating:
Colocations handled automatically by placer.


In [13]:
with tf.Session() as sess:
  sess.run(tf.global_variables_initializer()) # Initialize global variables
  print(sess.run(v2))
  
  print(sess.run(a, feed_dict={p:20})) #
  
  try:
    sess.run(a) # Need to feed values to evaluate
  except Exception as e:
    print("Error occured.")
    
  print(sess.run(v2)) # Variable is accesible

2.0
22.0
Error occured.
2.0


In [0]:
x = np.array([0,1,2,3,4,5,6,7,8,9,10])
y = np.array([0,2,4,6,8,10,12,14,16,18,22])

In [0]:
w = tf.Variable(0.0)

In [0]:
input_x = tf.placeholder(tf.float32)
input_y = tf.placeholder(tf.float32)

In [0]:
prediction = tf.multiply(w, x)
cost = tf.reduce_sum(tf.square(prediction - y)) # Mean squared error
optimizer = tf.train.GradientDescentOptimizer(0.01).minimize(cost) # Gradient Descent

In [18]:
with tf.Session() as sess:
  sess.run(tf.global_variables_initializer()) # Initialize variables
  print("w = ", sess.run(w))
  
  for i in range(5):
    optimized_result = sess.run(optimizer, feed_dict = {input_x:x, input_y:y})
    sess.run(prediction)
    print("cost = ", sess.run(cost))
    print("optimized result = ", optimized_result)
    print("w updated = ", sess.run(w))
    print("-------------------------")
  

w =  0.0
cost =  72771.39
optimized result =  None
w updated =  15.799999
-------------------------
cost =  3266578.0
optimized result =  None
w updated =  -90.06
-------------------------
cost =  146636540.0
optimized result =  None
w updated =  619.20197
-------------------------
cost =  6582514000.0
optimized result =  None
w updated =  -4132.853
-------------------------
cost =  295489000000.0
optimized result =  None
w updated =  27705.914
-------------------------


## Function Evaluation

We will evaluate the following expression: 
f(x,y) = xz + x^2 + z + 5 + 2x


*   x: Initialize a variable called x with a constant value of 5
*   z: Initialize a variable called z with a constant value of 6
*   c: Initialize a constant tensor called c with a constant value of 5
*   square: Initialize a constant tensor called square with a constant value of 2
*   f: Construct the operator

In [0]:
x = tf.get_variable("x", dtype=tf.int32,  initializer=tf.constant([5]))
z = tf.get_variable("z", dtype=tf.int32,  initializer=tf.constant([6]))
c = tf.constant([5], name =	"constant") 
square = tf.constant([2], name =	"square")
f = tf.multiply(x, z) + tf.pow(x, square) + z + c + tf.multiply(square, x)

In [20]:
init = tf.global_variables_initializer() # prepare to initialize all variables
with tf.Session() as sess:    
  init.run() # Initialize x and y    
  function_result = f.eval()
print(function_result)   

[76]


## Simple Linear Model

In [0]:
x = tf.placeholder(dtype=tf.float32, shape=(None,1))
y_true = tf.placeholder(dtype = tf.float32, shape = (None,1))

In [0]:
linear_model = tf.layers.Dense(units = 1, bias_initializer = tf.constant_initializer(1))
y_pred = linear_model(x)

In [23]:
loss = tf.losses.mean_squared_error(labels = y_true, predictions = y_pred)

Instructions for updating:
Use tf.cast instead.


In [0]:
optimizer = tf.train.GradientDescentOptimizer(0.01)
train = optimizer.minimize(loss)

In [0]:
init = tf.global_variables_initializer()

In [0]:
x_values = np.array([[1], [2], [3], [4]])
y_values = np.array([[0], [-1], [-2], [-3]])

In [27]:
with tf.Session() as sess:
  
  sess.run(init)
  
  for i in range(1000):
    _, loss_value = sess.run((train, loss), feed_dict = {x:x_values, y_true:y_values})
    print(loss_value, end='\r')
    
  weights = sess.run(linear_model.weights)
  bias = sess.run(linear_model.bias)
  preds = sess.run(y_pred, feed_dict = {x:x_values})
  
  print("The weight is: ", weights)
  print("The bias is: ", bias)
  print("The predictions are: \n", preds)

The weight is:  [array([[-1.0002282]], dtype=float32), array([1.0006711], dtype=float32)]
The bias is:  [1.0006711]
The predictions are: 
 [[ 4.4298172e-04]
 [-9.9978518e-01]
 [-2.0000134e+00]
 [-3.0002415e+00]]


In [0]:
# Get the weight
w = weights[0].tolist()[0][0]

In [0]:
# Get the bias
b = weights[1].tolist()[0]

In [30]:
# Make predictions based on the weight and bias
x_values * w + b

array([[ 4.42981720e-04],
       [-9.99785185e-01],
       [-2.00001335e+00],
       [-3.00024152e+00]])